### ISSUE TITLE
zabbix_sender error: 2

### ISSUE THREAD

**Issue by ArturOnGitHub** [ikzelf/zbxdb#72] opened 2021-03-11 09:01 UTC
**Describe the issue**
Install with document https://github.com/ikzelf/zbxdb/blob/master/doc/getting_started.md delete all conf files in etc/ except for Oracle, rename zbxdb.odb.cfg as name host of Oracle database in Zabbix zbxdb.Oracle.cfg and start cron jobs

Command:
cat $ZBXDB_HOME/log/zbxdb.Oracle.cfg.log
```
2021-03-10 12:13:02,416___main___50_Fatal messages
2021-03-10 12:13:02,416___main___50_Critical messages
2021-03-10 12:13:02,416___main___40_Error messages
2021-03-10 12:13:02,416___main___30_Warning message
2021-03-10 12:13:02,416___main___30_zbxdb found db_type=oracle, driver cx_Oracle; checking for driver

2021-03-10 12:13:02,535___main___40_connected db_url //Oracle:1521/dev type RDBMS db_role PRIMARY version 12
2021-03-10 12:13:02.535257 user zabbix ZABBIX sid,serial 142,2276 instance dev as normal cancel:True

2021-03-10 12:13:11,480___main___40_connect 1 times, 0 fail; started 37 queries, 2 fail memrss:27296 user:0.325245 sys:0.036590

2021-03-10 13:13:07,497___main___40_connect 1 times, 0 fail; started 440 queries, 2 fail memrss:27296 user:0.679801 sys:0.179249

2021-03-10 14:13:09,255___main___40_connect 1 times, 0 fail; started 843 queries, 2 fail memrss:27300 user:1.041702 sys:0.329757
```

Command:
ls $HOME/zbxdb_out
`zbxdb.Oracle.zbx`

Command:
cat $ZBXDB_HOME/log/zbxdb_sender.log
```
2021-03-11 11:25:02,102___main___30_Logging in /home/user1/log/zbxdb_sender.log
2021-03-11 11:25:02,104___main___30_Namespace(cfile='/etc/zabbix/zabbix_agentd.conf', verbosity=0, zbxdb_out='zbxdb_out')
2021-03-11 11:25:02,105___main___30_Using /etc/zabbix/zabbix_agentd.conf
2021-03-11 11:25:02,105___main___30_2021-03-11-1125 processing zbxdb.Oracle.zbx
2021-03-11 11:25:02,117___main___40_zabbix_sender zbxdb.Oracle.zbx error: 2
2021-03-11 11:25:02,134___main___30_removed lock /home/user1/zbxdb_sender/zbxdb_sender.lock
```

Command:
ls $HOME/etc/
`logging.json  logging.json.example  logging_sender.json  zbxdb_checks  zbxdb.Oracle.cfg  zbx_discover_oradbs.cfg`

Command:
ls $HOME/zbxdb_sender/in 
Is Empty 

Command:
ls $HOME/zbxdb_sender/archive
Show many zip archives

Command:
zabbix_sender -h
Show help about using zabbix_sender

Command:
cat /etc/zabbix/zabbix_agentd.conf
Show contents of zabbix_agentd.conf file

In Zabbix I don't see latest data and have problem "zbxdb Connect nodata Oracle since 30m". I use Zabbix 3.4.15. I install zbxdb before adding support SAPhana.

**I will be grateful for your help in resolving the issue.**

**Comment by ikzelf** [comment] 2021-03-11 10:58
Everything I see looks like OK. In $HOME/zbxdb_sender/archive you see the archives that are maintained in case you need to look back. It is the collection of the zbxdb_out/* files, taken every minute. I think your problem is a mismatch between the hostname parameter in zbxdb.Oracle.cfg and what you entered in the zabbix GUI. That is case sensitive and should be an exact match.
The error code that you see in zbxdb_sender.log is the exit code of zabbix_sender.
grep hostname $HOME/etc/zbxdb.Oracle.cfg

**Comment by ArturOnGitHub** [comment] 2021-03-11 12:56
Thanks for your feedback!
Yes, you are right, the host letter case did not match that of Zabbix. I fixed it and now I have the following result, in zbx_sender.log I still get error 2, but now Zabbix began to receive data, but not all that are defined in the template, but only some part.
The issue "zbxdb Connect nodata Oracle-Msk since 30m" has been resolved. There was a problem "rman [DB FULL] .last bkup OUDer 3d" "backups ouder dan 3d ..... wat klopt er niet?"
The main thing that I need to keep track of so that the space allocated for the flash recovery area does not overflow is somewhere in your template, but I have not had time to figure it out yet.

**Comment by ikzelf** [comment] 2021-03-11 13:04
For the flash recovery area see [http://ronr.blogspot.com/2015/10/how-to-create-new-metrics-for-zbxora.html](http://ronr.blogspot.com/2015/10/how-to-create-new-metrics-for-zbxora.html) I just don't update the template very often so there are quite a few items more queried than in the template. If you want them, just add them to the template and feel free to return a nicer, better template using a pull request.

It looks like your database has had a full backup more than 3 days ago. You can tweak this to your taste. In general the template tries to find with what interval backups are taken and tries to report when the next backup is not coming when it is expected. For this it is measuring the average backup age during the last month.

If you have any recommendations to make the tool or the documentation better, feel free to shout or even better, create a pull request with the improvements you made. Glad you got it up and running so easy.

**Comment by ArturOnGitHub** [comment] 2021-03-11 13:15
Thanks again for your answers! I really appreciate it. I will need some time to understand how your template works in zabbix. I also wanted to create a separate user to connect to the Oracle database for zbxdb. Can you advise what the minimum set of rights must be given to this user in Oracle in order for your solution to work correctly and collect all the necessary information?

**Comment by ArturOnGitHub** [comment] 2021-03-11 13:26
I also wanted to clarify if I can ignore the zabbix_sender error: 2 in zbxdb_sender.log if sending data to Zabbix now works?

**Comment by ikzelf** [comment] 2021-03-11 14:08
Hi, for oracle users check [https://github.com/ikzelf/zbxdb#database-user-creation](https://github.com/ikzelf/zbxdb#database-user-creation). In case you need to monitor a recovering standby database you also need sysdba privileges but I am sure you know about that.

As long as there are more items in the queries than there are in the template the error 2 will occur. As long as you receive the data you need, you can ignore that. For v11 someone added a nice performance metrics query. Those are not in the template and also not in the other versions. If you want that: feel free to add and send me a pull request for that. Error 1 is more problematic since that means no item received zabbix, but that will soon be noted by means of the nodata trigger.

**Comment by ikzelf** [comment] 2021-03-12 11:45
Do you need more help on this? (or tips on how to improve?)

**Comment by ArturOnGitHub** [comment] 2021-03-12 13:50
Good afternoon, thanks for your feedback!
I managed to add tracking flash recovery area, it was in your zabbix template and found a configuration file with a ready request and connected it, now I get the necessary data on the flash recovery area in zabbix. I have not yet figured out and did not understand how to add two different Oracle databases if they are both on the same host. I would like to sort this out. If it's not difficult for you, then write how to do it.

At the moment, I have the following suggestions for improvement:
1) Add to the description that the hostname is case sensitive and must match the hostname in zabbix
2) I would like to receive a more understandable error than Error: 2 in zbxdb_sender.log, and when sending data to zabbix starts to work, so that there are no errors in the log
3) I would like to see instructions on how to uninstall your solution (how to remove everything that is installed according to the document getting_started.md)

I want to thank you for the database monitoring add-on you developed and for your answers, I really appreciate it.

**Comment by ikzelf** [comment] 2021-03-12 14:17
I added a few lines to the trouble shooting text, hopefully that will help others.
zabbix_sender is not very helpful with the error codes. Sadly enough I can not do much more about that, other than pass in through in the log. As long as keys are generated in the SQL's that are not -yet- known in zabbix, there will be error code 2.
I will add de-install instructions, thanks for that.

For multiple databases on one host: zbxdb.py is just a regular database client, no more, no less. You have one configuration for each database. (for multi tenant zbxdb.py connect to the root container and for RAC you just connect using the scan listener and monitor using one single connection and configuration)

**Comment by ArturOnGitHub** [comment] 2021-03-14 16:16
Good afternoon, thanks again for your reply and for adding uninstallation instructions

I have a few questions:
1) I need to create a trigger for the maximum size of DATA files, I found you have the following value p_ts [MY_INSTANCE_NAME, MY_DATA_FILE, pctfreeMAX] looks like this is what I need, can you confirm this?
2) I would also like to create a value and trigger for the number of Oracle processes. I found you have parm [MY_INSTANCE_NAME, processes, value] and it shows the set number of processes.
I also found the following options
service [, MY_INSTANCE_NAME, SYS $ BACKGROUND, sess]
service [, MY_INSTANCE_NAME, SYS $ USERS, sess]
service [, MY_INSTANCE_NAME, MY_INSTANCE_NAME, sess]
I wanted to sum them up and compare them as a percentage with parm [MY_INSTANCE_NAME, processes, value]
But the parameters
service [, MY_INSTANCE_NAME, SYS $ BACKGROUND, sess]
service [, MY_INSTANCE_NAME, SYS $ USERS, sess]
service [, MY_INSTANCE_NAME, MY_INSTANCE_NAME, sess]
don't get values ​​in Zabbix, although if I execute the query from the file primary.12.cfg in SQL Developer:

```
service.cnt: select 'service['||decode (s.con_id,0, d.name, pdb.name)||','||i.instance_name||','|| s.service_name||',sess]' ,count(*)
               from gv$session s join gv$instance i
                 on (   s.inst_id = i.inst_id)
                                 left join v$containers pdb
                 on (   s.con_id = pdb.con_id)
                     cross join v$database d
                 group by i.instance_name, s.service_name, decode (s.con_id,0, d.name, pdb.name)
```

then I get the required values. I think the problem of passing values ​​to Zabbix lies in the names of the data columns returned by the query. Should they be KEY and VALUE?

**Comment by ikzelf** [comment] 2021-03-14 17:11
I have the setup of sizing based on tablespaces, not on datafiles.

The names/aliases of the queries have no value. The first column must deliver the key of a metric as it is listed in the GUI. The second column must be the value and have the correct datatype.

For values that are returning results in sql and don’t show up in zabbix: check the output files in the senders archive. It could be that I made an error. If you want and found a solution, create a pull request and I will be happy to accept that, automagically giving you the credits.

**Comment by ArturOnGitHub** [comment] 2021-03-15 10:21
Good afternoon, thanks for your answer! I tried to check one of the latest archives, I found the file zbxdb.Oracle-Msk.zbx and displayed its contents, in it I see the following line

Oracle-Msk "inst[INST_NAME,sessions]" 1615799342 339

in zabbix prototypes I see:

service[{#PDB},{#INST_NAME},{#SERVICE_NAME},sess]

In Zabbix Latest Data I see follow empty Items, first value in service Items is empty:

service[,INST_NAME,SERVICE_NAME,sess]
service[,INST_NAME,SERVICE_NAME,sess]
service[,INST_NAME,SERVICE_NAME,sess]

When I execute query in SQL Developer, I get the follow results, first value in service Items isn't empty:

service[INST_NAME,INST_NAME,SYS$BACKGROUND,sess]
service[INST_NAME,INST_NAME,SYS$USERS,sess]
service[INST_NAME,INST_NAME,TCPROD,sess]

I don't quite understand yet what the problem is.

I've barely used Git and I'm not sure yet if I can make a change request.

**Comment by ikzelf** [comment] 2021-03-15 11:16
Oracle "inst[INST_NAME,sessions]" 1615799342 339
comes from the sysstat query.

For the services, a lld query is used to define the macros that are fed into zabbix: service.lld

The first column in service[,INST_NAME,SERVICE_NAME,sess] should be the database name or the container name depending on classic or multi tenant database. The problem seems to be that the service.lld query keeps the "{#PDB}" macro empty in a classic database. This does not match service.cnt query that correctly gives dbname as first column.

I think that the service.lld should become:
select distinct decode (s.con_id,0, d.name, pdb.name) "{#PDB}", i.instance_name "{#INST_NAME}", s.name "{#SERVICE_NAME}"
               from gv$services s join gv$instance i
                 on (   s.inst_id = i.inst_id)
               cross join v$database d
               join gv$containers pdb
                 on (s.con_id = pdb.con_id)

Do you agree on that?

(BTW: in the lld queries, the column aliases are used to become the zabbix discovery macros)

**Comment by ikzelf** [comment] 2021-03-15 11:25
slightly better:
select decode (s.con_id,0, d.name, pdb.name) "{#PDB}", i.instance_name "{#INST_NAME}", nvl(s.name,s.network_name) "{#SERVICE_NAME}"
    from gv$services s join gv$instance i
       on (   s.inst_id = i.inst_id)
 cross join v$database d
 join gv$containers pdb
 on (s.con_id = pdb.con_id)

**Comment by ArturOnGitHub** [comment] 2021-03-15 12:36
Yes, it was with this request that the elements became correct and began to receive data. Thank you very much for your help!

I also wanted to clarify about the flash recovery area, in previous posts I asked you how to get data for the flash recovery area and you advised me to use your instructions http://ronr.blogspot.com/2015/10/how-to- create-new-metrics-for-zbxora.html
I added to the etc/zbxdb.Oracle.cfg file in site_checks my_super_checks and then I started getting data.
But now I noticed that there is the query in the etc/zbxdb_checks/ oracle/primary.12.cfg file:

```
fra: select 'fra[limit]', space_limit from v$recovery_file_dest def
      union all
     select 'fra[used]', space_used from v$recovery_file_dest def
      union all
     select 'fra[reclaimable]', space_reclaimable from v$recovery_file_dest def
      union all
     select 'fra[files]', number_of_files from v$recovery_file_dest def
      union all
     select 'fra[usable,pct]',decode(space_limit, 0,0,(100-(100*(space_used - space_reclaimable)/space_limit)))
       from v$recovery_file_dest
      union all
     select 'rp', count(*) from v$restore_point
```

It seemed to me that this query did not work for me.

Should this query work without adding it to the etc/zbxdb.Oracle.cfg file in site_checks my_super_checks?

**Comment by ikzelf** [comment] 2021-03-15 13:11
The fra query is in the primary.*.cfg so it should work. Are the fields defined in the template? Do you mean that the query failed?

The site_checks are meant to be used for very specific things like application specific queries that are not beneficial for all. I will change the service.lld query and push that.

**Comment by ArturOnGitHub** [comment] 2021-03-15 13:42
Thanks for your reply!
The elements in the template are defined, it seemed to me that I did not get values for these elements until I registered my_super_checks in site_checks
I will try to disable my_super_checks and see if zabbix receives data for flash recovery area items

**Comment by ikzelf** [comment] 2021-03-15 13:50
You can also check in zabbix for application zbxdb what the status of the fra query is.

**Comment by ArturOnGitHub** [comment] 2021-03-15 14:44
I disabled my_super_checks and zabbix gets data for flash recovery area items.
I also checked zbxdb in Zabbix for fra status OK.
I still do not understand everything about your template, but I have become better at understanding it, thanks for your help!
I will try to come back later to thank you.

**Comment by ikzelf** [comment] 2021-03-15 14:59
well, there is a lot in the template. It's a few years of work....
My goal was to make it simple and extendable.
Glad it all works as designed and I will now close this issue.
Thanks.

**Closed by ikzelf** 2021-03-15 14:59 UTC
